import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={"justify-center mx-auto flex flex-col items-center relative"}
      >
        <Header />
        <main className='h-screen flex flex-col bg-white'> 
          {children}
          <Navbar />
        </main>
      </body>
    </html>
  );
}
